language: go
go_import_path: github.com/CanDIG/go-model-service

go:
  - "1.8"
  - "1.9"
  - "1.10.x"

cache:
  directories:
    - ~/node_modules
    - ~/.nvm

before_install:
 - ./install_dep.sh
 - apt-get install -y nodejs npm # for dredd
 - apt-get install python-pip # for dreddhooks
 - npm install -g dredd
 - pip install dredd_hooks

install:
 - ./install.sh

script:
 - cd model-vs/api && dredd
