// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi A barebones service for variant calls
A model variant service demonstarting CanDIG API best practices


    Schemes:
      http
    Host: localhost
    BasePath: /
    Version: 1.0.0

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
