// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"net/http"
	"strings"

	errors "github.com/go-openapi/errors"
	loads "github.com/go-openapi/loads"
	runtime "github.com/go-openapi/runtime"
	middleware "github.com/go-openapi/runtime/middleware"
	security "github.com/go-openapi/runtime/security"
	spec "github.com/go-openapi/spec"
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGenericServiceAPI creates a new GenericService instance
func NewGenericServiceAPI(spec *loads.Document) *GenericServiceAPI {
	return &GenericServiceAPI{
		handlers:            make(map[string]map[string]http.Handler),
		formats:             strfmt.Default,
		defaultConsumes:     "application/json",
		defaultProduces:     "application/json",
		customConsumers:     make(map[string]runtime.Consumer),
		customProducers:     make(map[string]runtime.Producer),
		ServerShutdown:      func() {},
		spec:                spec,
		ServeError:          errors.ServeError,
		BasicAuthenticator:  security.BasicAuth,
		APIKeyAuthenticator: security.APIKeyAuth,
		BearerAuthenticator: security.BearerAuth,
		JSONConsumer:        runtime.JSONConsumer(),
		JSONProducer:        runtime.JSONProducer(),
		GetCallsHandler: GetCallsHandlerFunc(func(params GetCallsParams) middleware.Responder {
			return middleware.NotImplemented("operation GetCalls has not yet been implemented")
		}),
		GetIndividualsHandler: GetIndividualsHandlerFunc(func(params GetIndividualsParams) middleware.Responder {
			return middleware.NotImplemented("operation GetIndividuals has not yet been implemented")
		}),
		GetIndividualsByVariantHandler: GetIndividualsByVariantHandlerFunc(func(params GetIndividualsByVariantParams) middleware.Responder {
			return middleware.NotImplemented("operation GetIndividualsByVariant has not yet been implemented")
		}),
		GetOneCallHandler: GetOneCallHandlerFunc(func(params GetOneCallParams) middleware.Responder {
			return middleware.NotImplemented("operation GetOneCall has not yet been implemented")
		}),
		GetOneIndividualHandler: GetOneIndividualHandlerFunc(func(params GetOneIndividualParams) middleware.Responder {
			return middleware.NotImplemented("operation GetOneIndividual has not yet been implemented")
		}),
		GetOneVariantHandler: GetOneVariantHandlerFunc(func(params GetOneVariantParams) middleware.Responder {
			return middleware.NotImplemented("operation GetOneVariant has not yet been implemented")
		}),
		GetVariantsHandler: GetVariantsHandlerFunc(func(params GetVariantsParams) middleware.Responder {
			return middleware.NotImplemented("operation GetVariants has not yet been implemented")
		}),
		GetVariantsByIndividualHandler: GetVariantsByIndividualHandlerFunc(func(params GetVariantsByIndividualParams) middleware.Responder {
			return middleware.NotImplemented("operation GetVariantsByIndividual has not yet been implemented")
		}),
		PostCallHandler: PostCallHandlerFunc(func(params PostCallParams) middleware.Responder {
			return middleware.NotImplemented("operation PostCall has not yet been implemented")
		}),
		PostIndividualHandler: PostIndividualHandlerFunc(func(params PostIndividualParams) middleware.Responder {
			return middleware.NotImplemented("operation PostIndividual has not yet been implemented")
		}),
		PostVariantHandler: PostVariantHandlerFunc(func(params PostVariantParams) middleware.Responder {
			return middleware.NotImplemented("operation PostVariant has not yet been implemented")
		}),
	}
}

/*GenericServiceAPI A model variant service demonstarting CanDIG API best practices */
type GenericServiceAPI struct {
	spec            *loads.Document
	context         *middleware.Context
	handlers        map[string]map[string]http.Handler
	formats         strfmt.Registry
	customConsumers map[string]runtime.Consumer
	customProducers map[string]runtime.Producer
	defaultConsumes string
	defaultProduces string
	Middleware      func(middleware.Builder) http.Handler

	// BasicAuthenticator generates a runtime.Authenticator from the supplied basic auth function.
	// It has a default implemention in the security package, however you can replace it for your particular usage.
	BasicAuthenticator func(security.UserPassAuthentication) runtime.Authenticator
	// APIKeyAuthenticator generates a runtime.Authenticator from the supplied token auth function.
	// It has a default implemention in the security package, however you can replace it for your particular usage.
	APIKeyAuthenticator func(string, string, security.TokenAuthentication) runtime.Authenticator
	// BearerAuthenticator generates a runtime.Authenticator from the supplied bearer token auth function.
	// It has a default implemention in the security package, however you can replace it for your particular usage.
	BearerAuthenticator func(string, security.ScopedTokenAuthentication) runtime.Authenticator

	// JSONConsumer registers a consumer for a "application/json" mime type
	JSONConsumer runtime.Consumer

	// JSONProducer registers a producer for a "application/json" mime type
	JSONProducer runtime.Producer

	// GetCallsHandler sets the operation handler for the get calls operation
	GetCallsHandler GetCallsHandler
	// GetIndividualsHandler sets the operation handler for the get individuals operation
	GetIndividualsHandler GetIndividualsHandler
	// GetIndividualsByVariantHandler sets the operation handler for the get individuals by variant operation
	GetIndividualsByVariantHandler GetIndividualsByVariantHandler
	// GetOneCallHandler sets the operation handler for the get one call operation
	GetOneCallHandler GetOneCallHandler
	// GetOneIndividualHandler sets the operation handler for the get one individual operation
	GetOneIndividualHandler GetOneIndividualHandler
	// GetOneVariantHandler sets the operation handler for the get one variant operation
	GetOneVariantHandler GetOneVariantHandler
	// GetVariantsHandler sets the operation handler for the get variants operation
	GetVariantsHandler GetVariantsHandler
	// GetVariantsByIndividualHandler sets the operation handler for the get variants by individual operation
	GetVariantsByIndividualHandler GetVariantsByIndividualHandler
	// PostCallHandler sets the operation handler for the post call operation
	PostCallHandler PostCallHandler
	// PostIndividualHandler sets the operation handler for the post individual operation
	PostIndividualHandler PostIndividualHandler
	// PostVariantHandler sets the operation handler for the post variant operation
	PostVariantHandler PostVariantHandler

	// ServeError is called when an error is received, there is a default handler
	// but you can set your own with this
	ServeError func(http.ResponseWriter, *http.Request, error)

	// ServerShutdown is called when the HTTP(S) server is shut down and done
	// handling all active connections and does not accept connections any more
	ServerShutdown func()

	// Custom command line argument groups with their descriptions
	CommandLineOptionsGroups []swag.CommandLineOptionsGroup

	// User defined logger function.
	Logger func(string, ...interface{})
}

// SetDefaultProduces sets the default produces media type
func (o *GenericServiceAPI) SetDefaultProduces(mediaType string) {
	o.defaultProduces = mediaType
}

// SetDefaultConsumes returns the default consumes media type
func (o *GenericServiceAPI) SetDefaultConsumes(mediaType string) {
	o.defaultConsumes = mediaType
}

// SetSpec sets a spec that will be served for the clients.
func (o *GenericServiceAPI) SetSpec(spec *loads.Document) {
	o.spec = spec
}

// DefaultProduces returns the default produces media type
func (o *GenericServiceAPI) DefaultProduces() string {
	return o.defaultProduces
}

// DefaultConsumes returns the default consumes media type
func (o *GenericServiceAPI) DefaultConsumes() string {
	return o.defaultConsumes
}

// Formats returns the registered string formats
func (o *GenericServiceAPI) Formats() strfmt.Registry {
	return o.formats
}

// RegisterFormat registers a custom format validator
func (o *GenericServiceAPI) RegisterFormat(name string, format strfmt.Format, validator strfmt.Validator) {
	o.formats.Add(name, format, validator)
}

// Validate validates the registrations in the GenericServiceAPI
func (o *GenericServiceAPI) Validate() error {
	var unregistered []string

	if o.JSONConsumer == nil {
		unregistered = append(unregistered, "JSONConsumer")
	}

	if o.JSONProducer == nil {
		unregistered = append(unregistered, "JSONProducer")
	}

	if o.GetCallsHandler == nil {
		unregistered = append(unregistered, "GetCallsHandler")
	}

	if o.GetIndividualsHandler == nil {
		unregistered = append(unregistered, "GetIndividualsHandler")
	}

	if o.GetIndividualsByVariantHandler == nil {
		unregistered = append(unregistered, "GetIndividualsByVariantHandler")
	}

	if o.GetOneCallHandler == nil {
		unregistered = append(unregistered, "GetOneCallHandler")
	}

	if o.GetOneIndividualHandler == nil {
		unregistered = append(unregistered, "GetOneIndividualHandler")
	}

	if o.GetOneVariantHandler == nil {
		unregistered = append(unregistered, "GetOneVariantHandler")
	}

	if o.GetVariantsHandler == nil {
		unregistered = append(unregistered, "GetVariantsHandler")
	}

	if o.GetVariantsByIndividualHandler == nil {
		unregistered = append(unregistered, "GetVariantsByIndividualHandler")
	}

	if o.PostCallHandler == nil {
		unregistered = append(unregistered, "PostCallHandler")
	}

	if o.PostIndividualHandler == nil {
		unregistered = append(unregistered, "PostIndividualHandler")
	}

	if o.PostVariantHandler == nil {
		unregistered = append(unregistered, "PostVariantHandler")
	}

	if len(unregistered) > 0 {
		return fmt.Errorf("missing registration: %s", strings.Join(unregistered, ", "))
	}

	return nil
}

// ServeErrorFor gets a error handler for a given operation id
func (o *GenericServiceAPI) ServeErrorFor(operationID string) func(http.ResponseWriter, *http.Request, error) {
	return o.ServeError
}

// AuthenticatorsFor gets the authenticators for the specified security schemes
func (o *GenericServiceAPI) AuthenticatorsFor(schemes map[string]spec.SecurityScheme) map[string]runtime.Authenticator {

	return nil

}

// Authorizer returns the registered authorizer
func (o *GenericServiceAPI) Authorizer() runtime.Authorizer {

	return nil

}

// ConsumersFor gets the consumers for the specified media types
func (o *GenericServiceAPI) ConsumersFor(mediaTypes []string) map[string]runtime.Consumer {

	result := make(map[string]runtime.Consumer)
	for _, mt := range mediaTypes {
		switch mt {

		case "application/json":
			result["application/json"] = o.JSONConsumer

		}

		if c, ok := o.customConsumers[mt]; ok {
			result[mt] = c
		}
	}
	return result

}

// ProducersFor gets the producers for the specified media types
func (o *GenericServiceAPI) ProducersFor(mediaTypes []string) map[string]runtime.Producer {

	result := make(map[string]runtime.Producer)
	for _, mt := range mediaTypes {
		switch mt {

		case "application/json":
			result["application/json"] = o.JSONProducer

		}

		if p, ok := o.customProducers[mt]; ok {
			result[mt] = p
		}
	}
	return result

}

// HandlerFor gets a http.Handler for the provided operation method and path
func (o *GenericServiceAPI) HandlerFor(method, path string) (http.Handler, bool) {
	if o.handlers == nil {
		return nil, false
	}
	um := strings.ToUpper(method)
	if _, ok := o.handlers[um]; !ok {
		return nil, false
	}
	if path == "/" {
		path = ""
	}
	h, ok := o.handlers[um][path]
	return h, ok
}

// Context returns the middleware context for the generic service API
func (o *GenericServiceAPI) Context() *middleware.Context {
	if o.context == nil {
		o.context = middleware.NewRoutableContext(o.spec, o, nil)
	}

	return o.context
}

func (o *GenericServiceAPI) initHandlerCache() {
	o.Context() // don't care about the result, just that the initialization happened

	if o.handlers == nil {
		o.handlers = make(map[string]map[string]http.Handler)
	}

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/calls"] = NewGetCalls(o.context, o.GetCallsHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/individuals"] = NewGetIndividuals(o.context, o.GetIndividualsHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/variants/{variant_id}/individuals"] = NewGetIndividualsByVariant(o.context, o.GetIndividualsByVariantHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/calls/{call_id}"] = NewGetOneCall(o.context, o.GetOneCallHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/individuals/{individual_id}"] = NewGetOneIndividual(o.context, o.GetOneIndividualHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/variants/{variant_id}"] = NewGetOneVariant(o.context, o.GetOneVariantHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/variants"] = NewGetVariants(o.context, o.GetVariantsHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/individuals/{individual_id}/variants"] = NewGetVariantsByIndividual(o.context, o.GetVariantsByIndividualHandler)

	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/calls"] = NewPostCall(o.context, o.PostCallHandler)

	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/individuals"] = NewPostIndividual(o.context, o.PostIndividualHandler)

	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/variants"] = NewPostVariant(o.context, o.PostVariantHandler)

}

// Serve creates a http handler to serve the API over HTTP
// can be used directly in http.ListenAndServe(":8000", api.Serve(nil))
func (o *GenericServiceAPI) Serve(builder middleware.Builder) http.Handler {
	o.Init()

	if o.Middleware != nil {
		return o.Middleware(builder)
	}
	return o.context.APIHandler(builder)
}

// Init allows you to just initialize the handler cache, you can then recompose the middleware as you see fit
func (o *GenericServiceAPI) Init() {
	if len(o.handlers) == 0 {
		o.initHandlerCache()
	}
}

// RegisterConsumer allows you to add (or override) a consumer for a media type.
func (o *GenericServiceAPI) RegisterConsumer(mediaType string, consumer runtime.Consumer) {
	o.customConsumers[mediaType] = consumer
}

// RegisterProducer allows you to add (or override) a producer for a media type.
func (o *GenericServiceAPI) RegisterProducer(mediaType string, producer runtime.Producer) {
	o.customProducers[mediaType] = producer
}
