// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetOneVariantHandlerFunc turns a function with the right signature into a get one variant handler
type GetOneVariantHandlerFunc func(GetOneVariantParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetOneVariantHandlerFunc) Handle(params GetOneVariantParams) middleware.Responder {
	return fn(params)
}

// GetOneVariantHandler interface for that can handle valid get one variant params
type GetOneVariantHandler interface {
	Handle(GetOneVariantParams) middleware.Responder
}

// NewGetOneVariant creates a new http.Handler for the get one variant operation
func NewGetOneVariant(ctx *middleware.Context, handler GetOneVariantHandler) *GetOneVariant {
	return &GetOneVariant{Context: ctx, Handler: handler}
}

/*GetOneVariant swagger:route GET /variants/{variant_id} getOneVariant

Get specific variant

*/
type GetOneVariant struct {
	Context *middleware.Context
	Handler GetOneVariantHandler
}

func (o *GetOneVariant) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetOneVariantParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
