// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/CanDIG/go-model-service/model-vs/api/models"
)

// GetVariantsOKCode is the HTTP code returned for type GetVariantsOK
const GetVariantsOKCode int = 200

/*GetVariantsOK Return variants

swagger:response getVariantsOK
*/
type GetVariantsOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Variant `json:"body,omitempty"`
}

// NewGetVariantsOK creates GetVariantsOK with default headers values
func NewGetVariantsOK() *GetVariantsOK {

	return &GetVariantsOK{}
}

// WithPayload adds the payload to the get variants o k response
func (o *GetVariantsOK) WithPayload(payload []*models.Variant) *GetVariantsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get variants o k response
func (o *GetVariantsOK) SetPayload(payload []*models.Variant) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetVariantsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make([]*models.Variant, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// GetVariantsForbiddenCode is the HTTP code returned for type GetVariantsForbidden
const GetVariantsForbiddenCode int = 403

/*GetVariantsForbidden Forbidden to query for all variants

swagger:response getVariantsForbidden
*/
type GetVariantsForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetVariantsForbidden creates GetVariantsForbidden with default headers values
func NewGetVariantsForbidden() *GetVariantsForbidden {

	return &GetVariantsForbidden{}
}

// WithPayload adds the payload to the get variants forbidden response
func (o *GetVariantsForbidden) WithPayload(payload *models.Error) *GetVariantsForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get variants forbidden response
func (o *GetVariantsForbidden) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetVariantsForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetVariantsInternalServerErrorCode is the HTTP code returned for type GetVariantsInternalServerError
const GetVariantsInternalServerErrorCode int = 500

/*GetVariantsInternalServerError Internal error

swagger:response getVariantsInternalServerError
*/
type GetVariantsInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetVariantsInternalServerError creates GetVariantsInternalServerError with default headers values
func NewGetVariantsInternalServerError() *GetVariantsInternalServerError {

	return &GetVariantsInternalServerError{}
}

// WithPayload adds the payload to the get variants internal server error response
func (o *GetVariantsInternalServerError) WithPayload(payload *models.Error) *GetVariantsInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get variants internal server error response
func (o *GetVariantsInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetVariantsInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
