// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/validate"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetOneIndividualParams creates a new GetOneIndividualParams object
// no default values defined in spec.
func NewGetOneIndividualParams() GetOneIndividualParams {

	return GetOneIndividualParams{}
}

// GetOneIndividualParams contains all the bound params for the get one individual operation
// typically these are obtained from a http.Request
//
// swagger:parameters get_one_individual
type GetOneIndividualParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Individual unique identifier
	  Required: true
	  In: path
	*/
	IndividualID strfmt.UUID
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetOneIndividualParams() beforehand.
func (o *GetOneIndividualParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rIndividualID, rhkIndividualID, _ := route.Params.GetOK("individual_id")
	if err := o.bindIndividualID(rIndividualID, rhkIndividualID, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetOneIndividualParams) bindIndividualID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	// Format: uuid
	value, err := formats.Parse("uuid", raw)
	if err != nil {
		return errors.InvalidType("individual_id", "path", "strfmt.UUID", raw)
	}
	o.IndividualID = *(value.(*strfmt.UUID))

	if err := o.validateIndividualID(formats); err != nil {
		return err
	}

	return nil
}

func (o *GetOneIndividualParams) validateIndividualID(formats strfmt.Registry) error {

	if err := validate.FormatOf("individual_id", "path", "uuid", o.IndividualID.String(), formats); err != nil {
		return err
	}

	return nil
}
