// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetOneCallHandlerFunc turns a function with the right signature into a get one call handler
type GetOneCallHandlerFunc func(GetOneCallParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetOneCallHandlerFunc) Handle(params GetOneCallParams) middleware.Responder {
	return fn(params)
}

// GetOneCallHandler interface for that can handle valid get one call params
type GetOneCallHandler interface {
	Handle(GetOneCallParams) middleware.Responder
}

// NewGetOneCall creates a new http.Handler for the get one call operation
func NewGetOneCall(ctx *middleware.Context, handler GetOneCallHandler) *GetOneCall {
	return &GetOneCall{Context: ctx, Handler: handler}
}

/*GetOneCall swagger:route GET /calls/{call_id} getOneCall

Get specific call

*/
type GetOneCall struct {
	Context *middleware.Context
	Handler GetOneCallHandler
}

func (o *GetOneCall) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetOneCallParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
