// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetIndividualsHandlerFunc turns a function with the right signature into a get individuals handler
type GetIndividualsHandlerFunc func(GetIndividualsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetIndividualsHandlerFunc) Handle(params GetIndividualsParams) middleware.Responder {
	return fn(params)
}

// GetIndividualsHandler interface for that can handle valid get individuals params
type GetIndividualsHandler interface {
	Handle(GetIndividualsParams) middleware.Responder
}

// NewGetIndividuals creates a new http.Handler for the get individuals operation
func NewGetIndividuals(ctx *middleware.Context, handler GetIndividualsHandler) *GetIndividuals {
	return &GetIndividuals{Context: ctx, Handler: handler}
}

/*GetIndividuals swagger:route GET /individuals getIndividuals

Get all individuals

*/
type GetIndividuals struct {
	Context *middleware.Context
	Handler GetIndividualsHandler
}

func (o *GetIndividuals) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetIndividualsParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
