// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/CanDIG/go-model-service/variant-service/api/models"
)

// GetIndividualsByVariantOKCode is the HTTP code returned for type GetIndividualsByVariantOK
const GetIndividualsByVariantOKCode int = 200

/*GetIndividualsByVariantOK Return individuals

swagger:response getIndividualsByVariantOK
*/
type GetIndividualsByVariantOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Individual `json:"body,omitempty"`
}

// NewGetIndividualsByVariantOK creates GetIndividualsByVariantOK with default headers values
func NewGetIndividualsByVariantOK() *GetIndividualsByVariantOK {

	return &GetIndividualsByVariantOK{}
}

// WithPayload adds the payload to the get individuals by variant o k response
func (o *GetIndividualsByVariantOK) WithPayload(payload []*models.Individual) *GetIndividualsByVariantOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get individuals by variant o k response
func (o *GetIndividualsByVariantOK) SetPayload(payload []*models.Individual) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetIndividualsByVariantOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make([]*models.Individual, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// GetIndividualsByVariantNotFoundCode is the HTTP code returned for type GetIndividualsByVariantNotFound
const GetIndividualsByVariantNotFoundCode int = 404

/*GetIndividualsByVariantNotFound Variant does not exist

swagger:response getIndividualsByVariantNotFound
*/
type GetIndividualsByVariantNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetIndividualsByVariantNotFound creates GetIndividualsByVariantNotFound with default headers values
func NewGetIndividualsByVariantNotFound() *GetIndividualsByVariantNotFound {

	return &GetIndividualsByVariantNotFound{}
}

// WithPayload adds the payload to the get individuals by variant not found response
func (o *GetIndividualsByVariantNotFound) WithPayload(payload *models.Error) *GetIndividualsByVariantNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get individuals by variant not found response
func (o *GetIndividualsByVariantNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetIndividualsByVariantNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
