// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetCallsHandlerFunc turns a function with the right signature into a get calls handler
type GetCallsHandlerFunc func(GetCallsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetCallsHandlerFunc) Handle(params GetCallsParams) middleware.Responder {
	return fn(params)
}

// GetCallsHandler interface for that can handle valid get calls params
type GetCallsHandler interface {
	Handle(GetCallsParams) middleware.Responder
}

// NewGetCalls creates a new http.Handler for the get calls operation
func NewGetCalls(ctx *middleware.Context, handler GetCallsHandler) *GetCalls {
	return &GetCalls{Context: ctx, Handler: handler}
}

/*GetCalls swagger:route GET /calls getCalls

Get all calls

*/
type GetCalls struct {
	Context *middleware.Context
	Handler GetCallsHandler
}

func (o *GetCalls) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetCallsParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
