// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/CanDIG/go-model-service/variant-service/api/models"
)

// GetIndividualsOKCode is the HTTP code returned for type GetIndividualsOK
const GetIndividualsOKCode int = 200

/*GetIndividualsOK Return individuals

swagger:response getIndividualsOK
*/
type GetIndividualsOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Individual `json:"body,omitempty"`
}

// NewGetIndividualsOK creates GetIndividualsOK with default headers values
func NewGetIndividualsOK() *GetIndividualsOK {

	return &GetIndividualsOK{}
}

// WithPayload adds the payload to the get individuals o k response
func (o *GetIndividualsOK) WithPayload(payload []*models.Individual) *GetIndividualsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get individuals o k response
func (o *GetIndividualsOK) SetPayload(payload []*models.Individual) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetIndividualsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make([]*models.Individual, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// GetIndividualsInternalServerErrorCode is the HTTP code returned for type GetIndividualsInternalServerError
const GetIndividualsInternalServerErrorCode int = 500

/*GetIndividualsInternalServerError Internal error

swagger:response getIndividualsInternalServerError
*/
type GetIndividualsInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetIndividualsInternalServerError creates GetIndividualsInternalServerError with default headers values
func NewGetIndividualsInternalServerError() *GetIndividualsInternalServerError {

	return &GetIndividualsInternalServerError{}
}

// WithPayload adds the payload to the get individuals internal server error response
func (o *GetIndividualsInternalServerError) WithPayload(payload *models.Error) *GetIndividualsInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get individuals internal server error response
func (o *GetIndividualsInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetIndividualsInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
