// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/CanDIG/go-model-service/variant-service/api/models"
)

// GetVariantsByIndividualOKCode is the HTTP code returned for type GetVariantsByIndividualOK
const GetVariantsByIndividualOKCode int = 200

/*GetVariantsByIndividualOK Return individuals

swagger:response getVariantsByIndividualOK
*/
type GetVariantsByIndividualOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Variant `json:"body,omitempty"`
}

// NewGetVariantsByIndividualOK creates GetVariantsByIndividualOK with default headers values
func NewGetVariantsByIndividualOK() *GetVariantsByIndividualOK {

	return &GetVariantsByIndividualOK{}
}

// WithPayload adds the payload to the get variants by individual o k response
func (o *GetVariantsByIndividualOK) WithPayload(payload []*models.Variant) *GetVariantsByIndividualOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get variants by individual o k response
func (o *GetVariantsByIndividualOK) SetPayload(payload []*models.Variant) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetVariantsByIndividualOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make([]*models.Variant, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// GetVariantsByIndividualNotFoundCode is the HTTP code returned for type GetVariantsByIndividualNotFound
const GetVariantsByIndividualNotFoundCode int = 404

/*GetVariantsByIndividualNotFound Individual does not exist

swagger:response getVariantsByIndividualNotFound
*/
type GetVariantsByIndividualNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetVariantsByIndividualNotFound creates GetVariantsByIndividualNotFound with default headers values
func NewGetVariantsByIndividualNotFound() *GetVariantsByIndividualNotFound {

	return &GetVariantsByIndividualNotFound{}
}

// WithPayload adds the payload to the get variants by individual not found response
func (o *GetVariantsByIndividualNotFound) WithPayload(payload *models.Error) *GetVariantsByIndividualNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get variants by individual not found response
func (o *GetVariantsByIndividualNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetVariantsByIndividualNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
