// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetIndividualsByVariantHandlerFunc turns a function with the right signature into a get individuals by variant handler
type GetIndividualsByVariantHandlerFunc func(GetIndividualsByVariantParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetIndividualsByVariantHandlerFunc) Handle(params GetIndividualsByVariantParams) middleware.Responder {
	return fn(params)
}

// GetIndividualsByVariantHandler interface for that can handle valid get individuals by variant params
type GetIndividualsByVariantHandler interface {
	Handle(GetIndividualsByVariantParams) middleware.Responder
}

// NewGetIndividualsByVariant creates a new http.Handler for the get individuals by variant operation
func NewGetIndividualsByVariant(ctx *middleware.Context, handler GetIndividualsByVariantHandler) *GetIndividualsByVariant {
	return &GetIndividualsByVariant{Context: ctx, Handler: handler}
}

/*GetIndividualsByVariant swagger:route GET /variants/{variant_id}/individuals getIndividualsByVariant

Get individuals with a given variant called

*/
type GetIndividualsByVariant struct {
	Context *middleware.Context
	Handler GetIndividualsByVariantHandler
}

func (o *GetIndividualsByVariant) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetIndividualsByVariantParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
