// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/CanDIG/go-model-service/variant-service/api/models"
)

// GetOneVariantOKCode is the HTTP code returned for type GetOneVariantOK
const GetOneVariantOKCode int = 200

/*GetOneVariantOK Return variant

swagger:response getOneVariantOK
*/
type GetOneVariantOK struct {

	/*
	  In: Body
	*/
	Payload *models.Variant `json:"body,omitempty"`
}

// NewGetOneVariantOK creates GetOneVariantOK with default headers values
func NewGetOneVariantOK() *GetOneVariantOK {

	return &GetOneVariantOK{}
}

// WithPayload adds the payload to the get one variant o k response
func (o *GetOneVariantOK) WithPayload(payload *models.Variant) *GetOneVariantOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get one variant o k response
func (o *GetOneVariantOK) SetPayload(payload *models.Variant) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetOneVariantOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetOneVariantNotFoundCode is the HTTP code returned for type GetOneVariantNotFound
const GetOneVariantNotFoundCode int = 404

/*GetOneVariantNotFound Variant not found

swagger:response getOneVariantNotFound
*/
type GetOneVariantNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetOneVariantNotFound creates GetOneVariantNotFound with default headers values
func NewGetOneVariantNotFound() *GetOneVariantNotFound {

	return &GetOneVariantNotFound{}
}

// WithPayload adds the payload to the get one variant not found response
func (o *GetOneVariantNotFound) WithPayload(payload *models.Error) *GetOneVariantNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get one variant not found response
func (o *GetOneVariantNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetOneVariantNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetOneVariantInternalServerErrorCode is the HTTP code returned for type GetOneVariantInternalServerError
const GetOneVariantInternalServerErrorCode int = 500

/*GetOneVariantInternalServerError Internal error

swagger:response getOneVariantInternalServerError
*/
type GetOneVariantInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetOneVariantInternalServerError creates GetOneVariantInternalServerError with default headers values
func NewGetOneVariantInternalServerError() *GetOneVariantInternalServerError {

	return &GetOneVariantInternalServerError{}
}

// WithPayload adds the payload to the get one variant internal server error response
func (o *GetOneVariantInternalServerError) WithPayload(payload *models.Error) *GetOneVariantInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get one variant internal server error response
func (o *GetOneVariantInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetOneVariantInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
