// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/CanDIG/go-model-service/variant-service/api/models"
)

// GetOneResourceOKCode is the HTTP code returned for type GetOneResourceOK
const GetOneResourceOKCode int = 200

/*GetOneResourceOK Return resource

swagger:response getOneResourceOK
*/
type GetOneResourceOK struct {

	/*
	  In: Body
	*/
	Payload *models.Resource `json:"body,omitempty"`
}

// NewGetOneResourceOK creates GetOneResourceOK with default headers values
func NewGetOneResourceOK() *GetOneResourceOK {

	return &GetOneResourceOK{}
}

// WithPayload adds the payload to the get one resource o k response
func (o *GetOneResourceOK) WithPayload(payload *models.Resource) *GetOneResourceOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get one resource o k response
func (o *GetOneResourceOK) SetPayload(payload *models.Resource) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetOneResourceOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetOneResourceNotFoundCode is the HTTP code returned for type GetOneResourceNotFound
const GetOneResourceNotFoundCode int = 404

/*GetOneResourceNotFound Resource not found

swagger:response getOneResourceNotFound
*/
type GetOneResourceNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Resource `json:"body,omitempty"`
}

// NewGetOneResourceNotFound creates GetOneResourceNotFound with default headers values
func NewGetOneResourceNotFound() *GetOneResourceNotFound {

	return &GetOneResourceNotFound{}
}

// WithPayload adds the payload to the get one resource not found response
func (o *GetOneResourceNotFound) WithPayload(payload *models.Resource) *GetOneResourceNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get one resource not found response
func (o *GetOneResourceNotFound) SetPayload(payload *models.Resource) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetOneResourceNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetOneResourceInternalServerErrorCode is the HTTP code returned for type GetOneResourceInternalServerError
const GetOneResourceInternalServerErrorCode int = 500

/*GetOneResourceInternalServerError Internal error

swagger:response getOneResourceInternalServerError
*/
type GetOneResourceInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetOneResourceInternalServerError creates GetOneResourceInternalServerError with default headers values
func NewGetOneResourceInternalServerError() *GetOneResourceInternalServerError {

	return &GetOneResourceInternalServerError{}
}

// WithPayload adds the payload to the get one resource internal server error response
func (o *GetOneResourceInternalServerError) WithPayload(payload *models.Error) *GetOneResourceInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get one resource internal server error response
func (o *GetOneResourceInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetOneResourceInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
