// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/validate"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetIndividualsByVariantParams creates a new GetIndividualsByVariantParams object
// no default values defined in spec.
func NewGetIndividualsByVariantParams() GetIndividualsByVariantParams {

	return GetIndividualsByVariantParams{}
}

// GetIndividualsByVariantParams contains all the bound params for the get individuals by variant operation
// typically these are obtained from a http.Request
//
// swagger:parameters get_individuals_by_variant
type GetIndividualsByVariantParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Variant unique identifier
	  Required: true
	  In: path
	*/
	VariantID strfmt.UUID
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetIndividualsByVariantParams() beforehand.
func (o *GetIndividualsByVariantParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rVariantID, rhkVariantID, _ := route.Params.GetOK("variant_id")
	if err := o.bindVariantID(rVariantID, rhkVariantID, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetIndividualsByVariantParams) bindVariantID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	// Format: uuid
	value, err := formats.Parse("uuid", raw)
	if err != nil {
		return errors.InvalidType("variant_id", "path", "strfmt.UUID", raw)
	}
	o.VariantID = *(value.(*strfmt.UUID))

	if err := o.validateVariantID(formats); err != nil {
		return err
	}

	return nil
}

func (o *GetIndividualsByVariantParams) validateVariantID(formats strfmt.Registry) error {

	if err := validate.FormatOf("variant_id", "path", "uuid", o.VariantID.String(), formats); err != nil {
		return err
	}

	return nil
}
