// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/CanDIG/go-model-service/variant-service/api/models"
)

// GetOneCallOKCode is the HTTP code returned for type GetOneCallOK
const GetOneCallOKCode int = 200

/*GetOneCallOK Return call

swagger:response getOneCallOK
*/
type GetOneCallOK struct {

	/*
	  In: Body
	*/
	Payload *models.Call `json:"body,omitempty"`
}

// NewGetOneCallOK creates GetOneCallOK with default headers values
func NewGetOneCallOK() *GetOneCallOK {

	return &GetOneCallOK{}
}

// WithPayload adds the payload to the get one call o k response
func (o *GetOneCallOK) WithPayload(payload *models.Call) *GetOneCallOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get one call o k response
func (o *GetOneCallOK) SetPayload(payload *models.Call) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetOneCallOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetOneCallNotFoundCode is the HTTP code returned for type GetOneCallNotFound
const GetOneCallNotFoundCode int = 404

/*GetOneCallNotFound Call not found

swagger:response getOneCallNotFound
*/
type GetOneCallNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetOneCallNotFound creates GetOneCallNotFound with default headers values
func NewGetOneCallNotFound() *GetOneCallNotFound {

	return &GetOneCallNotFound{}
}

// WithPayload adds the payload to the get one call not found response
func (o *GetOneCallNotFound) WithPayload(payload *models.Error) *GetOneCallNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get one call not found response
func (o *GetOneCallNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetOneCallNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetOneCallInternalServerErrorCode is the HTTP code returned for type GetOneCallInternalServerError
const GetOneCallInternalServerErrorCode int = 500

/*GetOneCallInternalServerError Internal error

swagger:response getOneCallInternalServerError
*/
type GetOneCallInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetOneCallInternalServerError creates GetOneCallInternalServerError with default headers values
func NewGetOneCallInternalServerError() *GetOneCallInternalServerError {

	return &GetOneCallInternalServerError{}
}

// WithPayload adds the payload to the get one call internal server error response
func (o *GetOneCallInternalServerError) WithPayload(payload *models.Error) *GetOneCallInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get one call internal server error response
func (o *GetOneCallInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetOneCallInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
