// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// MainGetVariantsHandlerFunc turns a function with the right signature into a main get variants handler
type MainGetVariantsHandlerFunc func(MainGetVariantsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn MainGetVariantsHandlerFunc) Handle(params MainGetVariantsParams) middleware.Responder {
	return fn(params)
}

// MainGetVariantsHandler interface for that can handle valid main get variants params
type MainGetVariantsHandler interface {
	Handle(MainGetVariantsParams) middleware.Responder
}

// NewMainGetVariants creates a new http.Handler for the main get variants operation
func NewMainGetVariants(ctx *middleware.Context, handler MainGetVariantsHandler) *MainGetVariants {
	return &MainGetVariants{Context: ctx, Handler: handler}
}

/*MainGetVariants swagger:route GET /variants mainGetVariants

Get all variants within genomic range

*/
type MainGetVariants struct {
	Context *middleware.Context
	Handler MainGetVariantsHandler
}

func (o *MainGetVariants) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewMainGetVariantsParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
