// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// MainPostVariantHandlerFunc turns a function with the right signature into a main post variant handler
type MainPostVariantHandlerFunc func(MainPostVariantParams) middleware.Responder

// Handle executing the request and returning a response
func (fn MainPostVariantHandlerFunc) Handle(params MainPostVariantParams) middleware.Responder {
	return fn(params)
}

// MainPostVariantHandler interface for that can handle valid main post variant params
type MainPostVariantHandler interface {
	Handle(MainPostVariantParams) middleware.Responder
}

// NewMainPostVariant creates a new http.Handler for the main post variant operation
func NewMainPostVariant(ctx *middleware.Context, handler MainPostVariantHandler) *MainPostVariant {
	return &MainPostVariant{Context: ctx, Handler: handler}
}

/*MainPostVariant swagger:route POST /variants mainPostVariant

Add a variant to the database

*/
type MainPostVariant struct {
	Context *middleware.Context
	Handler MainPostVariantHandler
}

func (o *MainPostVariant) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewMainPostVariantParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
