// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// PostCallHandlerFunc turns a function with the right signature into a post call handler
type PostCallHandlerFunc func(PostCallParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostCallHandlerFunc) Handle(params PostCallParams) middleware.Responder {
	return fn(params)
}

// PostCallHandler interface for that can handle valid post call params
type PostCallHandler interface {
	Handle(PostCallParams) middleware.Responder
}

// NewPostCall creates a new http.Handler for the post call operation
func NewPostCall(ctx *middleware.Context, handler PostCallHandler) *PostCall {
	return &PostCall{Context: ctx, Handler: handler}
}

/*PostCall swagger:route POST /calls postCall

Add a call to the database

*/
type PostCall struct {
	Context *middleware.Context
	Handler PostCallHandler
}

func (o *PostCall) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPostCallParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
