// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/CanDIG/go-model-service/variant-service/api/models"
)

// PostIndividualCreatedCode is the HTTP code returned for type PostIndividualCreated
const PostIndividualCreatedCode int = 201

/*PostIndividualCreated New individual created

swagger:response postIndividualCreated
*/
type PostIndividualCreated struct {
	/*

	 */
	Location string `json:"Location"`

	/*
	  In: Body
	*/
	Payload *models.Individual `json:"body,omitempty"`
}

// NewPostIndividualCreated creates PostIndividualCreated with default headers values
func NewPostIndividualCreated() *PostIndividualCreated {

	return &PostIndividualCreated{}
}

// WithLocation adds the location to the post individual created response
func (o *PostIndividualCreated) WithLocation(location string) *PostIndividualCreated {
	o.Location = location
	return o
}

// SetLocation sets the location to the post individual created response
func (o *PostIndividualCreated) SetLocation(location string) {
	o.Location = location
}

// WithPayload adds the payload to the post individual created response
func (o *PostIndividualCreated) WithPayload(payload *models.Individual) *PostIndividualCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post individual created response
func (o *PostIndividualCreated) SetPayload(payload *models.Individual) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostIndividualCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header Location

	location := o.Location
	if location != "" {
		rw.Header().Set("Location", location)
	}

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostIndividualMethodNotAllowedCode is the HTTP code returned for type PostIndividualMethodNotAllowed
const PostIndividualMethodNotAllowedCode int = 405

/*PostIndividualMethodNotAllowed Forbidden to overwrite individual in post

swagger:response postIndividualMethodNotAllowed
*/
type PostIndividualMethodNotAllowed struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostIndividualMethodNotAllowed creates PostIndividualMethodNotAllowed with default headers values
func NewPostIndividualMethodNotAllowed() *PostIndividualMethodNotAllowed {

	return &PostIndividualMethodNotAllowed{}
}

// WithPayload adds the payload to the post individual method not allowed response
func (o *PostIndividualMethodNotAllowed) WithPayload(payload *models.Error) *PostIndividualMethodNotAllowed {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post individual method not allowed response
func (o *PostIndividualMethodNotAllowed) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostIndividualMethodNotAllowed) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(405)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostIndividualInternalServerErrorCode is the HTTP code returned for type PostIndividualInternalServerError
const PostIndividualInternalServerErrorCode int = 500

/*PostIndividualInternalServerError Internal error - Individual not created

swagger:response postIndividualInternalServerError
*/
type PostIndividualInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostIndividualInternalServerError creates PostIndividualInternalServerError with default headers values
func NewPostIndividualInternalServerError() *PostIndividualInternalServerError {

	return &PostIndividualInternalServerError{}
}

// WithPayload adds the payload to the post individual internal server error response
func (o *PostIndividualInternalServerError) WithPayload(payload *models.Error) *PostIndividualInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post individual internal server error response
func (o *PostIndividualInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostIndividualInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
