// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// PostVariantHandlerFunc turns a function with the right signature into a post variant handler
type PostVariantHandlerFunc func(PostVariantParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostVariantHandlerFunc) Handle(params PostVariantParams) middleware.Responder {
	return fn(params)
}

// PostVariantHandler interface for that can handle valid post variant params
type PostVariantHandler interface {
	Handle(PostVariantParams) middleware.Responder
}

// NewPostVariant creates a new http.Handler for the post variant operation
func NewPostVariant(ctx *middleware.Context, handler PostVariantHandler) *PostVariant {
	return &PostVariant{Context: ctx, Handler: handler}
}

/*PostVariant swagger:route POST /variants postVariant

Add a variant to the database

*/
type PostVariant struct {
	Context *middleware.Context
	Handler PostVariantHandler
}

func (o *PostVariant) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPostVariantParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
