// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/mauricelam/genny

package handlers

import (
	"github.com/CanDIG/go-model-service/variant-service/api/restapi/operations"

	"github.com/go-openapi/runtime/middleware"

	"github.com/CanDIG/go-model-service/variant-service/transformations"

	"github.com/CanDIG/go-model-service/variant-service/errors"

	"github.com/CanDIG/go-model-service/variant-service/api/restapi/handlers/utilities"

	apimodels "github.com/CanDIG/go-model-service/variant-service/api/models"
)

// PostIndividual processes a Individual posted by the API request and creates it into the database.
// It then retrieves the newly created Individual from the database and returns it, along with its URL location.
func PostIndividual(params operations.PostIndividualParams) middleware.Responder {
	funcName := "handlers.Post"

	tx, errPayload := utilities.ConnectDevelopment(funcName)
	if errPayload != nil {
		return operations.NewPostIndividualInternalServerError().WithPayload(errPayload)
	}

	_, err := getIndividualByID(params.Individual.ID.String(), tx)
	if err == nil { // TODO this is not a great check
		message := "This Individual already exists in the database. " +
			"It cannot be overwritten with POST; please use PUT instead."
		errors.Log(nil, 405, funcName, message)
		errPayload := &apimodels.Error{Code: 405001, Message: &message}
		return operations.NewPostIndividualMethodNotAllowed().WithPayload(errPayload)
	}

	newIndividual, errPayload := transformations.IndividualAPIToDataModel(*params.Individual, tx)
	if errPayload != nil {
		return operations.NewPostIndividualInternalServerError().WithPayload(errPayload)
	}

	err = tx.Create(newIndividual)
	if err != nil {
		errors.Log(err, 500, funcName,
			"Create into database failed")
		errPayload := errors.DefaultInternalServerError()
		return operations.NewPostIndividualInternalServerError().WithPayload(errPayload)
	}

	retrievedDataIndividual, err := getIndividualByID(newIndividual.ID.String(), tx)
	if err != nil {
		errors.Log(err, 500, funcName,
			"Failed to get Individual by ID from database immediately following its creation")
		errPayload := errors.DefaultInternalServerError()
		return operations.NewPostIndividualInternalServerError().WithPayload(errPayload)
	}

	retrievedAPIIndividual, errPayload := transformations.IndividualDataToAPIModel(*retrievedDataIndividual)
	if err != nil {
		return operations.NewPostIndividualInternalServerError().WithPayload(errPayload)
	}

	location := params.HTTPRequest.URL.Host + params.HTTPRequest.URL.EscapedPath() +
		"/" + retrievedAPIIndividual.ID.String()
	return operations.NewPostIndividualCreated().WithPayload(retrievedAPIIndividual).WithLocation(location)
}

// PostVariant processes a Variant posted by the API request and creates it into the database.
// It then retrieves the newly created Variant from the database and returns it, along with its URL location.
func PostVariant(params operations.PostVariantParams) middleware.Responder {
	funcName := "handlers.Post"

	tx, errPayload := utilities.ConnectDevelopment(funcName)
	if errPayload != nil {
		return operations.NewPostVariantInternalServerError().WithPayload(errPayload)
	}

	_, err := getVariantByID(params.Variant.ID.String(), tx)
	if err == nil { // TODO this is not a great check
		message := "This Variant already exists in the database. " +
			"It cannot be overwritten with POST; please use PUT instead."
		errors.Log(nil, 405, funcName, message)
		errPayload := &apimodels.Error{Code: 405001, Message: &message}
		return operations.NewPostVariantMethodNotAllowed().WithPayload(errPayload)
	}

	newVariant, errPayload := transformations.VariantAPIToDataModel(*params.Variant, tx)
	if errPayload != nil {
		return operations.NewPostVariantInternalServerError().WithPayload(errPayload)
	}

	err = tx.Create(newVariant)
	if err != nil {
		errors.Log(err, 500, funcName,
			"Create into database failed")
		errPayload := errors.DefaultInternalServerError()
		return operations.NewPostVariantInternalServerError().WithPayload(errPayload)
	}

	retrievedDataVariant, err := getVariantByID(newVariant.ID.String(), tx)
	if err != nil {
		errors.Log(err, 500, funcName,
			"Failed to get Variant by ID from database immediately following its creation")
		errPayload := errors.DefaultInternalServerError()
		return operations.NewPostVariantInternalServerError().WithPayload(errPayload)
	}

	retrievedAPIVariant, errPayload := transformations.VariantDataToAPIModel(*retrievedDataVariant)
	if err != nil {
		return operations.NewPostVariantInternalServerError().WithPayload(errPayload)
	}

	location := params.HTTPRequest.URL.Host + params.HTTPRequest.URL.EscapedPath() +
		"/" + retrievedAPIVariant.ID.String()
	return operations.NewPostVariantCreated().WithPayload(retrievedAPIVariant).WithLocation(location)
}
