// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/mauricelam/genny

package handlers

import (
	"github.com/gobuffalo/pop"

	datamodels "github.com/CanDIG/go-model-service/variant-service/data/models"
)

// getIndividualByID returns the Individual in the database corresponding to the given ID (or nil if no match is found)
func getIndividualByID(id string, tx *pop.Connection) (*datamodels.Individual, error) {
	resource := &datamodels.Individual{}
	err := tx.Find(resource, id)
	return resource, err
}

// getVariantByID returns the Variant in the database corresponding to the given ID (or nil if no match is found)
func getVariantByID(id string, tx *pop.Connection) (*datamodels.Variant, error) {
	resource := &datamodels.Variant{}
	err := tx.Find(resource, id)
	return resource, err
}
