// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/CanDIG/genny

package handlers

import (
	"github.com/gobuffalo/pop"

	datamodels "github.com/CanDIG/go-model-service/variant-service/data/models"
)

// getIndividualByID returns the Individual in the database corresponding to the given ID (or nil if no match is found)
func getIndividualByID(id string, tx *pop.Connection) (*datamodels.Individual, error) {
	Individual := &datamodels.Individual{}
	err := tx.Find(Individual, id)
	return Individual, err
}

// getVariantByID returns the Variant in the database corresponding to the given ID (or nil if no match is found)
func getVariantByID(id string, tx *pop.Connection) (*datamodels.Variant, error) {
	Variant := &datamodels.Variant{}
	err := tx.Find(Variant, id)
	return Variant, err
}

// getCallByID returns the Call in the database corresponding to the given ID (or nil if no match is found)
func getCallByID(id string, tx *pop.Connection) (*datamodels.Call, error) {
	Call := &datamodels.Call{}
	err := tx.Find(Call, id)
	return Call, err
}
