// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/CanDIG/genny

package handlers

import (
	"github.com/CanDIG/go-model-service/model-vs/api/restapi/operations"

	"github.com/go-openapi/runtime/middleware"

	"github.com/CanDIG/go-model-service/model-vs/errors"

	"github.com/CanDIG/go-model-service/model-vs/api/restapi/handlers/utilities"

	apimodels "github.com/CanDIG/go-model-service/model-vs/api/models"

	datamodels "github.com/CanDIG/go-model-service/model-vs/data/models"
)

// GetIndividuals returns all Individuals in the database given zero or more query parameters.
// The query parameters are handled separately in getIndividualsQuery.
func GetIndividuals(params operations.GetIndividualsParams) middleware.Responder {
	funcName := "handlers.GetIndividuals"

	tx, errPayload := utilities.ConnectDevelopment(funcName)
	if errPayload != nil {
		return operations.NewPostIndividualInternalServerError().WithPayload(errPayload)
	}

	// the full error response is handled here rather than the payload because a variety of http codes may occur
	query, errResponse := utilities.GetIndividuals(params, tx)
	if errResponse != nil {
		return errResponse
	}

	var dataIndividuals []datamodels.Individual
	err := query.All(&dataIndividuals)
	if err != nil {
		errors.Log(err, 500, funcName, "Problems getting Individuals from database")
		errPayload := errors.DefaultInternalServerError()
		return operations.NewGetIndividualsInternalServerError().WithPayload(errPayload)
	}

	var apiIndividuals []*apimodels.Individual
	for _, dataIndividual := range dataIndividuals {
		apiIndividual, errPayload := individualDataToAPIModel(dataIndividual)
		if errPayload != nil {
			return operations.NewGetIndividualsInternalServerError().WithPayload(errPayload)
		}
		apiIndividuals = append(apiIndividuals, apiIndividual)
	}

	return operations.NewGetIndividualsOK().WithPayload(apiIndividuals)
}

// GetVariants returns all Variants in the database given zero or more query parameters.
// The query parameters are handled separately in getVariantsQuery.
func GetVariants(params operations.GetVariantsParams) middleware.Responder {
	funcName := "handlers.GetVariants"

	tx, errPayload := utilities.ConnectDevelopment(funcName)
	if errPayload != nil {
		return operations.NewPostVariantInternalServerError().WithPayload(errPayload)
	}

	// the full error response is handled here rather than the payload because a variety of http codes may occur
	query, errResponse := utilities.GetVariants(params, tx)
	if errResponse != nil {
		return errResponse
	}

	var dataVariants []datamodels.Variant
	err := query.All(&dataVariants)
	if err != nil {
		errors.Log(err, 500, funcName, "Problems getting Variants from database")
		errPayload := errors.DefaultInternalServerError()
		return operations.NewGetVariantsInternalServerError().WithPayload(errPayload)
	}

	var apiVariants []*apimodels.Variant
	for _, dataVariant := range dataVariants {
		apiVariant, errPayload := variantDataToAPIModel(dataVariant)
		if errPayload != nil {
			return operations.NewGetVariantsInternalServerError().WithPayload(errPayload)
		}
		apiVariants = append(apiVariants, apiVariant)
	}

	return operations.NewGetVariantsOK().WithPayload(apiVariants)
}

// GetCalls returns all Calls in the database given zero or more query parameters.
// The query parameters are handled separately in getCallsQuery.
func GetCalls(params operations.GetCallsParams) middleware.Responder {
	funcName := "handlers.GetCalls"

	tx, errPayload := utilities.ConnectDevelopment(funcName)
	if errPayload != nil {
		return operations.NewPostCallInternalServerError().WithPayload(errPayload)
	}

	// the full error response is handled here rather than the payload because a variety of http codes may occur
	query, errResponse := utilities.GetCalls(params, tx)
	if errResponse != nil {
		return errResponse
	}

	var dataCalls []datamodels.Call
	err := query.All(&dataCalls)
	if err != nil {
		errors.Log(err, 500, funcName, "Problems getting Calls from database")
		errPayload := errors.DefaultInternalServerError()
		return operations.NewGetCallsInternalServerError().WithPayload(errPayload)
	}

	var apiCalls []*apimodels.Call
	for _, dataCall := range dataCalls {
		apiCall, errPayload := callDataToAPIModel(dataCall)
		if errPayload != nil {
			return operations.NewGetCallsInternalServerError().WithPayload(errPayload)
		}
		apiCalls = append(apiCalls, apiCall)
	}

	return operations.NewGetCallsOK().WithPayload(apiCalls)
}
