// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "A model variant service demonstarting CanDIG API best practices",
    "title": "A barebones service for variant calls",
    "version": "1.0.0"
  },
  "paths": {
    "/variants": {
      "get": {
        "summary": "Get all variants within genomic range",
        "operationId": "main.get_variants",
        "parameters": [
          {
            "pattern": "^[a-zA-Z0-9]*$",
            "type": "string",
            "name": "chromosome",
            "in": "query"
          },
          {
            "minimum": 1,
            "type": "integer",
            "name": "start",
            "in": "query"
          },
          {
            "minimum": 1,
            "type": "integer",
            "name": "end",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "Return variants",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Variant"
              }
            }
          },
          "500": {
            "description": "Internal error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "post": {
        "summary": "Add a variant to the database",
        "operationId": "main.post_variant",
        "parameters": [
          {
            "name": "variant",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/Variant"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "New variant created",
            "schema": {
              "$ref": "#/definitions/Variant"
            },
            "headers": {
              "Location": {
                "type": "string"
              }
            }
          },
          "400": {
            "description": "Variant provided in body does not pass schema validation",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "405": {
            "description": "Forbidden to overwrite variant in put",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Internal error - Variant not created",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Call": {
      "type": "object",
      "required": [
        "individual_id",
        "variant_id",
        "genotype"
      ],
      "properties": {
        "created": {
          "description": "Creation time",
          "type": "string",
          "format": "date-time",
          "readOnly": true,
          "example": "2017-07-21T17:32:28Z"
        },
        "format": {
          "description": "Additional call information",
          "type": "string",
          "default": "",
          "maxLength": 100,
          "minLength": 0,
          "example": "GQ:DP:HQ 48:1:51,51"
        },
        "genotype": {
          "description": "Called genotype",
          "type": "string",
          "example": "0/1"
        },
        "id": {
          "description": "Unique internal identifier",
          "type": "string",
          "format": "uuid",
          "readOnly": true,
          "example": "bf3ba75b-8dfe-4619-b832-31c4a087a589"
        },
        "individual_id": {
          "description": "Unique internal identifier for the subject",
          "type": "integer",
          "format": "int64",
          "example": 123
        },
        "variant_id": {
          "description": "Unique internal identifier for the variant",
          "type": "integer",
          "format": "int64",
          "example": 123
        }
      }
    },
    "Error": {
      "type": "object",
      "required": [
        "message"
      ],
      "properties": {
        "code": {
          "type": "integer",
          "format": "int32"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "Individual": {
      "type": "object",
      "required": [
        "description"
      ],
      "properties": {
        "created": {
          "description": "Creation time",
          "type": "string",
          "format": "date-time",
          "readOnly": true,
          "example": "2017-07-21T17:32:28Z"
        },
        "description": {
          "description": "Description of subject (may be external identifier)",
          "type": "string",
          "maxLength": 100,
          "minLength": 1,
          "example": "Subject 17"
        },
        "id": {
          "description": "Unique internal identifier",
          "type": "string",
          "format": "uuid",
          "readOnly": true,
          "example": "bf3ba75b-8dfe-4619-b832-31c4a087a589"
        }
      }
    },
    "Variant": {
      "type": "object",
      "required": [
        "chromosome",
        "start",
        "ref",
        "alt"
      ],
      "properties": {
        "alt": {
          "description": "Alternate (variant) bases",
          "type": "string",
          "example": "A"
        },
        "chromosome": {
          "description": "Chromosome that the variant occurs on",
          "type": "string",
          "maxLength": 10,
          "minLength": 1,
          "example": "chr1"
        },
        "id": {
          "description": "Unique internal identifier",
          "type": "string",
          "format": "uuid",
          "readOnly": true,
          "example": "bf3ba75b-8dfe-4619-b832-31c4a087a589"
        },
        "name": {
          "description": "Variant name, if any",
          "type": "string",
          "default": "",
          "maxLength": 100,
          "minLength": 0,
          "example": "rs6054257"
        },
        "ref": {
          "description": "Reference bases",
          "type": "string",
          "example": "G"
        },
        "start": {
          "description": "Beginning location of variant",
          "type": "integer",
          "minimum": 1,
          "example": 14370
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "A model variant service demonstarting CanDIG API best practices",
    "title": "A barebones service for variant calls",
    "version": "1.0.0"
  },
  "paths": {
    "/variants": {
      "get": {
        "summary": "Get all variants within genomic range",
        "operationId": "main.get_variants",
        "parameters": [
          {
            "pattern": "^[a-zA-Z0-9]*$",
            "type": "string",
            "name": "chromosome",
            "in": "query"
          },
          {
            "minimum": 1,
            "type": "integer",
            "name": "start",
            "in": "query"
          },
          {
            "minimum": 1,
            "type": "integer",
            "name": "end",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "Return variants",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Variant"
              }
            }
          },
          "500": {
            "description": "Internal error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "post": {
        "summary": "Add a variant to the database",
        "operationId": "main.post_variant",
        "parameters": [
          {
            "name": "variant",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/Variant"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "New variant created",
            "schema": {
              "$ref": "#/definitions/Variant"
            },
            "headers": {
              "Location": {
                "type": "string"
              }
            }
          },
          "400": {
            "description": "Variant provided in body does not pass schema validation",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "405": {
            "description": "Forbidden to overwrite variant in put",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Internal error - Variant not created",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Call": {
      "type": "object",
      "required": [
        "individual_id",
        "variant_id",
        "genotype"
      ],
      "properties": {
        "created": {
          "description": "Creation time",
          "type": "string",
          "format": "date-time",
          "readOnly": true,
          "example": "2017-07-21T17:32:28Z"
        },
        "format": {
          "description": "Additional call information",
          "type": "string",
          "default": "",
          "maxLength": 100,
          "minLength": 0,
          "example": "GQ:DP:HQ 48:1:51,51"
        },
        "genotype": {
          "description": "Called genotype",
          "type": "string",
          "example": "0/1"
        },
        "id": {
          "description": "Unique internal identifier",
          "type": "string",
          "format": "uuid",
          "readOnly": true,
          "example": "bf3ba75b-8dfe-4619-b832-31c4a087a589"
        },
        "individual_id": {
          "description": "Unique internal identifier for the subject",
          "type": "integer",
          "format": "int64",
          "example": 123
        },
        "variant_id": {
          "description": "Unique internal identifier for the variant",
          "type": "integer",
          "format": "int64",
          "example": 123
        }
      }
    },
    "Error": {
      "type": "object",
      "required": [
        "message"
      ],
      "properties": {
        "code": {
          "type": "integer",
          "format": "int32"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "Individual": {
      "type": "object",
      "required": [
        "description"
      ],
      "properties": {
        "created": {
          "description": "Creation time",
          "type": "string",
          "format": "date-time",
          "readOnly": true,
          "example": "2017-07-21T17:32:28Z"
        },
        "description": {
          "description": "Description of subject (may be external identifier)",
          "type": "string",
          "maxLength": 100,
          "minLength": 1,
          "example": "Subject 17"
        },
        "id": {
          "description": "Unique internal identifier",
          "type": "string",
          "format": "uuid",
          "readOnly": true,
          "example": "bf3ba75b-8dfe-4619-b832-31c4a087a589"
        }
      }
    },
    "Variant": {
      "type": "object",
      "required": [
        "chromosome",
        "start",
        "ref",
        "alt"
      ],
      "properties": {
        "alt": {
          "description": "Alternate (variant) bases",
          "type": "string",
          "example": "A"
        },
        "chromosome": {
          "description": "Chromosome that the variant occurs on",
          "type": "string",
          "maxLength": 10,
          "minLength": 1,
          "example": "chr1"
        },
        "id": {
          "description": "Unique internal identifier",
          "type": "string",
          "format": "uuid",
          "readOnly": true,
          "example": "bf3ba75b-8dfe-4619-b832-31c4a087a589"
        },
        "name": {
          "description": "Variant name, if any",
          "type": "string",
          "default": "",
          "maxLength": 100,
          "minLength": 0,
          "example": "rs6054257"
        },
        "ref": {
          "description": "Reference bases",
          "type": "string",
          "example": "G"
        },
        "start": {
          "description": "Beginning location of variant",
          "type": "integer",
          "minimum": 1,
          "example": 14370
        }
      }
    }
  }
}`))
}
